### ISSUE TITLE
Performa Satellite Error: API returned: Missing parameter: nonce

### ISSUE THREAD

**Issue by martin-ro** [jhuckaby/performa-satellite#6]
Running `/opt/performa/satellite.bin --debug` returns an error `Warning: Performa Satellite Error: API returned: Missing parameter: nonce` on one specific server. 

Trying to send fake data `/opt/performa/satellite.bin --fake`:
`Performa Satellite Error: API returned: Missing parameter: nonce`

I have 12 other server setup with the exact same config and can't figure out what's going wrong with this one. 

Any pointers appreciated.

**Comment by jhuckaby** [comment]
Oh dear, I'm so sorry you ran into this.  Someone found a [serious security flaw](https://github.com/jhuckaby/performa/issues/24) in the way Performa Satellite authenticates with Performa Server, and I had to redesign the whole system.

The problem you're having is that you probably downloaded a new Performa Satellite for your 13th server, but you're still running an old Performa which it communicates with.

You'll either have to upgrade ALL your servers running Performa Satellite and Performa to the latest version (1.1.4), OR you can download an older Performa Satellite (i.e. v1.1.3) which should work with your older Performa Server install.

To install an older satellite, use these commands:

```sh
mkdir /opt/performa
curl -L https://github.com/jhuckaby/performa-satellite/releases/download/v1.1.4/performa-satellite-linux-x64 > /opt/performa/satellite.bin
chmod 755 /opt/performa/satellite.bin
/opt/performa/satellite.bin --install
```

Again, I'm terribly sorry.  I was hoping I could do this upgrade and no one would run into any problems, but I failed to foresee someone installing the latest Performa Satellite, but not upgrading Performa Server itself.  Damn.

I couldn't figure out a way to do this in a backward-compatible way, because I had to tear out the entire authentication mechanism and redesign it.

**Comment by martin-ro** [comment]
Thanks a lot @jhuckaby! I just updated Performa and all satellite scripts and everything works perfectly again. 
Appreciate the the fast response and the work you put into this great monitoring tool.
