### ISSUE TITLE
How to download version 1.5 ?

### ISSUE THREAD

**Issue by sseodate** [jhuckaby/performa-satellite#7]
I did as the guide as readme guide:

1. Run the code:
 mkdir /opt/performa
 curl -L https://github.com/jhuckaby/performa-satellite/releases/latest/download/performa-satellite-linux-x64 > /opt/performa/satellite.bin
chmod 755 /opt/performa/satellite.bin

 /opt/performa/satellite.bin --install

Performa Satellite has been installed to cron:
        /etc/cron.d/performa-satellite

It is look like the last time i did it.
After i run perfoma it show the error: /opt/performa/satellite.bin
Performa Satellite Error: API returned: Missing parameter: nonce

Try to debug it:
/opt/performa/satellite.bin --debug
Warning: Performa Satellite Error: API returned: Missing parameter: nonce
{
        "version": "1.0",  
        "date": 1720797301.205,
>>> still in version 1.0 ??? 

How to get the latest version ?

**Comment by jhuckaby** [comment]
That's just the API format version.  You can ignore that.  It's always 1.0.  You have the latest Satellite version.

The problem is that Performa and Satellite recently changed, due to a [major security issue](https://github.com/jhuckaby/performa/issues/24) someone found, and I had to immediately upgrade both the server and the satellite to address this.  Unfortunately this required a breaking change.

You'll need to upgrade both your master Performa server, and all your satellite installs, to the latest.  Instructions [here](https://github.com/jhuckaby/performa#upgrading) (for server) and [here](https://github.com/jhuckaby/performa-satellite#installation) (for satellite).

Very sorry for the inconvenience over this.  I wouldn't have made such a big breaking change, but it was a severe critical security issue.

**Comment by sseodate** [comment]
Thanks man! I try to upgrade the Server Performa and it work perfect now! This one is a miracle and easy to use for me for months! Thanks a lot!
